server:
  port: 8089

spring:
  application:
    name: SERVICE-VOITURE
  cloud:
    consul:
      host: localhost       # Consul agent host
      port: 8500            # Consul agent port
      discovery:
        enabled: true       # Enable Consul service discovery
        service-name: service-voiture # Explicit service name for registration
        health-check-path: /actuator/health # Health check path for Consul
        health-check-interval: 10s         # Optional: Interval for health checks
